spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
camunda:
  bpm:
    default-serialization-format: "application/json"
spring:
  rabbitmq:
    host: 84.201.129.64
    password: Integration6
    username: odministrator
  jpa:
    hibernate:
      ddl-auto: update

